# Build the Docker image to make sure it works
name: docker-build-test

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths:
      # See `.dockerignore` for more details.
      - ".github/workflows/docker-build-test.yaml" # Include workflow itself
      - ".dockerignore"
      - "Dockerfile"
      - "go.mod"
      - "go.sum"
      - "cmd/**"
      - "data/**"
      - "internal/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: build Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: false
          load: true
          tags: test-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: test Docker image
        run: |
          docker image ls
          docker run --rm test-${{ github.sha }} --version || true
          echo "âœ… Docker image built successfully!"
