# Checks for typos in the repository
name: typos

permissions:
  contents: read

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  typos:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

    - name: spell check repo
      uses: crate-ci/typos@80c8a4945eec0f6d464eaf9e65ed98ef085283d1 # v1.38.1
