# Checks for typos in the repository
name: typos

permissions:
  contents: read

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  typos:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

    - name: spell check repo
      uses: crate-ci/typos@2d0ce569feab1f8752f1dde43cc2f2aa53236e06 # v1.40.0
